name: NASA Project CI
on: 
  push:
    branches: [ mac-review1 ]
  workflow_dispatch:
  pull_request:
    branches: [ mac-review1 ]
jobs: 
  build:
    env: 
      CI: true
      MONGO_URL: mongodb://localhost/Project0
    strategy:
      matrix: 
        node-version: [14.x, 16.x]
        mongodb-version: ['6.0']
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoEB from GitHub actions/checkout
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      
      # Test MongoDB Connection
      - name: Test MongoDB Connection
        run: mongo --eval "db.stats()" --quiet

      # List MongoDB Databases
      - name: List MongoDB Databases
        run: mongo --eval "printjson(db.adminCommand('listDatabases'))"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --prefix client

      - name: Run tests
        run: npm test